name: Analyse SonarQube

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  sonar:
    name: Analyse de Code avec SonarQube
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Installer Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Maven
        run: mvn clean install

      - name: Analyse SonarQube
        run: mvn sonar:sonar \
        -Dsonar.projectKey=springboot-app \
        -Dsonar.host.url=http://192.168.138.132:9000 \
        -Dsonar.login=${{ secrets.SONAR_SECRET }}
